version: "3.9"
services:
  fastapi:
    build:
      context: ./fastapi-app
    container_name: fastapi-todos
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-app:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

